#!/bin/bash

# ============================
# CREATION DES DIFFERENTS PATH
#
# Variables :
#   - ROOT_PIPE
#   - ROOT_CHANTIER
#   - ROOT_ARCHIVES
#
#   - TYPE
#   - ROOT_TYPE
# ============================

#root_pipe="/home/fabrice/OneDrive/Documents/_Documents/PIPELINE"



# root_pipe :
# fold_pipe :
# path_pipe :

fold_pipe="PIPELINE"
if [[ $SYSTEM == "linux" ]]; then
    root_pipe="/media/partage/PIPELINE/pipe/"
    path_pipe=${root_pipe}${fold_pipe}"/"

elif [[ $SYSTEM == "windows" ]]; then
    root_pipe="/mnt/p/pipe/"
    path_pipe=${root_pipe}${fold_pipe}"/"

    root_pipe_w="P:\\pipe\\"
    path_pipe_w=${root_pipe_w}${fold_pipe}"\\"

elif [[ $SYSTEM == "mac" ]]; then
    root_pipe="/Volumes/Pipeline/pipe/"
    path_pipe=${root_pipe}${fold_pipe}"/"
fi

# root_chantier :
# fold_chantier :
# path_chantier :

root_chantier=${path_pipe}
fold_chantier="chantier"
path_chantier=${root_chantier}${fold_chantier}


# root_archives :
# fold_archives :
# path_archives :

root_archives=${path_pipe}
fold_archives="archives"
path_archives=${root_archives}${fold_archives}


if [[ -e "${path_pipe}" ]]; then
    if [[ $AUTORUN == 0 ]]; then

        export ROOT_PIPE=${root_pipe}
        export FOLD_PIPE=${fold_pipe}
        export PATH_PIPE=${path_pipe}
        export ROOT_CHANTIER=${root_chantier}
        export FOLD_CHANTIER=${fold_chantier}
        export PATH_CHANTIER=${path_chantier}
        export ROOT_ARCHIVES=${root_archives}
        export FOLD_ARCHIVES=${fold_archives}
        export PATH_ARCHIVES=${path_archives}

    elif [[ $AUTORUN == 1 ]]; then
        pass
    fi
else
    echo " Le chemin vers le dossier $path_chantier ne peut pas être atteint. Aucune variable générée."
fi






# Résultat :
# ========================================================

#if ! [[ -e "$path_chantier" ]]; then
#    echo " Le chemin vers le dossier $path_chantier ne peut pas être atteint. Aucune variable générée."
#else
#    if [[ $AUTORUN == 0 ]]; then
##        export TYPE="3d"
#        export TYPE=""
#        export PROJ=""
#        export FOLD=""
#        export SOFT=""
#
#
#        export ROOT_PIPE="$root_pipe"
#        export ROOT_CHANTIER="$root_chantier"
#        export ROOT_ARCHIVES="$root_archives"
#        if [[ $SYSTEM == "windows" ]]; then # (Pour Windows)
#            export ROOT_PIPE_W="$root_pipe_w"
#        fi
#
##        export ROOT_TYPE="$ROOT_CHANTIER/$TYPE"
#        export ROOT_TYPE=""
#        export ROOT_PROJ=""
#        export ROOT_FOLD=""
#        export ROOT_SOFT=""
#
#    elif [[ $AUTORUN == 1 ]]; then
#        source "$BIN/data/autorun.sh"
#
#        export ROOT_SOFT=""
#
#        export ROOT_PIPE="$root_pipe"
#        export ROOT_CHANTIER="$root_chantier"
#        export ROOT_ARCHIVES="$root_archives"
#        if [[ $SYSTEM == "windows" ]]; then # (Pour Windows)
#            export ROOT_PIPE_W="$root_pipe_w"
#        fi
#
#        export ROOT_TYPE="$ROOT_CHANTIER/$TYPE"
#        export ROOT_PROJ="$ROOT_TYPE/$PROJ"
#        export ROOT_FOLD="$ROOT_PROJ/$FOLD"
#        export ROOT_SOFT=""
#    fi
#
#    if [[ $VERBOSE -ge 1 ]]; then
#        echo "verbose : $VERBOSE"
#    fi
#    if [[ $VERBOSE -ge 1 ]]; then
#        echo "BIN            = $BIN"
#        echo "ROOT_PIPE      = $ROOT_PIPE"
#        echo "ROOT_CHANTIER = $ROOT_CHANTIER${NEUTRE}"
#        echo "ROOT_ARCHIVES  = $ROOT_ARCHIVES${NEUTRE}"
#    fi
#
#fi

source "$BIN/data/autorun.sh"
