#!/bin/bash

# INIT 01 : Creation de la variable verbose

verbose=0

init() {
    if [[ $1 == "" ]];then
        export VERBOSE=0
    fi
    if [[ $# == 1 ]];then
        export VERBOSE=$1
    fi

    source "$BIN/init_02"
    if [[ $VERBOSE == 0 ]];then
        setprojet
    fi
}




