#!/usr/bin/env bash
#!/bin/bash







## BIN :
#alias tr='source $BIN/prog/pipe-ui/data/transfert.sh'
#
#alias p3="python3.6"
#alias ptest='cd ~/bin/prog/_training/Test/test_ui/; p3 executer.py &'
#alias sa='cd ~/bin/prog/pipe-ui/; p3 exec.py; cd - &'
#alias sat='cd ~/bin/prog/pipe-ui/; p3 load_form_ui.py; cd - &'
#
#alias un='fmbrc'
#
#alias deux='fmrc'
#

#
#
#
## MAIN :
#
#alias j='job'
#
#
#

#
#alias rmm='rm -Rf'
#alias ddu="du -h -d 1"
#
#alias nau="nn"
#alias py="python"
#

#
#
#
#
#
#
#
## PIPE
#
##alias run='job'
#alias jh='job -h'
#alias jha='job -ha' ###### ??
#alias kp="killpipe"
#alias jl="jll"
#
#alias s="setproj"
#alias sp="setproj"
#alias s1="setproj"
#
#alias jj="setshot"
#alias ss="setshot"
#alias s2="setshot"
#
#alias jjj="setdiscipline"
#alias sss="setdiscipline"
#alias sd="setdiscipline"
#alias s3="setdiscipline"
#
#
#
## SOFTS :
#

#alias ge='gedit'
#alias gd='gedit'
#
#
### SE DEPLACER :
#
#alias tyty="cd $BIN/prog/_training/Test/"
#
#
##alias gocache="cd $CACHE"
##alias gorender="cd $RENDER"
#
#alias goc='gocache'
#alias gor='gorender'
#alias goz='gozbrush'
#
#alias hip="gohip"
#
#alias cin="clear; cd /cygdrive/k; cll"
#alias pipe="cd $PIPE_ROOT"
#
#
#
## PRATIQUE :
#
#alias shtd="$ROOTC/WINDOWS/system32/shutdown.exe -s"
#
#alias brc="$EDITOR /home/$USER/.bashrc"
#alias brcs="source /home/$USER/.bashrc"
#alias sv="$EDITOR '$BIN/backup/savedFiles.txt'"
#
#
#alias d1='du --max-depth=1 -h'
#alias d2='du --max-depth=2 -h'
#
#
## PROG
#
alias pycin="python $BIN/../prog/cineteque/main2.py"
#
#
#
## NON TRIE
#
#alias bin="cd $BIN; clear; echo 'BIN :';echo '====='; ls -lah"
#alias binl="cd /home/$USER/bin; echo 'BIN LOCAL:';echo '==========='; ls -lah"
#
#alias rf="cd $SHOT_PATH/divers/ref; nn"
