#!/usr/bin/env bash
#!/bin/bash


# SET
# ----------------------------------------------------------------

alias t="run type"
alias p="run proj"
alias f="run fold"

alias r="run"

alias rt="type_remove"

alias z="python $BIN/python/test.py"


# CANA
# ----------------------------------------------------------------

alias bin="cd $BIN; clear; ls -lah"

alias binenv=". $BIN/venv/bin/activate"













































alias ii="ui main_window; python '$BIN/gui/main.py'; exit"


#alias gedit="/mnt/c/'Program Files'/'Sublime Text'/sublime_text.exe"

export EDITOR='gedit'

alias sublime="/usr/bin/subl"
alias sub=sublime


alias i="export AUTORUN=0; init"
alias i0="init 0"
alias i1="init 1"
alias i2="init 2"
alias i3="init 3"


# ----------------------------------------------------------------------------------------------------------------------
# ENVIRONNEMENT
# ----------------------------------------------------------------------------------------------------------------------



alias ~='cd ~'





# ----------------------------------------------------------------------------------------------------------------------
# ALIASES
# ---------------------------------------------------------------------------------------------------------------------- 


# SYSTEME

alias 4k="xrandr -s 3840x2160"
alias 2k="xrandr -s 2560x1440"
alias hd="xrandr -s 1920x1080"

alias su="sudo su"

alias ed="$EDITOR '$BIN/ed/$SYSTEM/aliases_$SYSTEM'"
alias ed2="$EDITOR '$BIN/ed/$SYSTEM/softs_$SYSTEM'"
alias eds="source $BIN/ed/$SYSTEM/aliases_$SYSTEM;source $BIN/ed/$SYSTEM/softs_$SYSTEM"

alias ls="ls --color=auto"

alias l="ls -lAvh"
alias ll="ls -lAvh"
alias lll="ls -lAvh"
alias cl="clear"
alias cll="clear; l"
#alias nn="open ."
alias nn="nautilus ."
alias brc="$EDITOR ~/.bashrc"





alias smb="$EDITOR /etc/samba/smb.conf"
alias fst="$EDITOR /etc/fstab"

alias ram="free -h && sysctl vm.drop_caches=3 && free -h"
alias rv="/mnt/c/'Program Files'/DJV2/bin/djv.com"
#"C:\Program Files\DJV2\bin\djv.exe"

alias shtd="$ROOT_C/WINDOWS/system32/shutdown.exe -s"
alias sh1='sudo shutdown -h +60'
alias sh2='sudo shutdown -h +120'
alias sh3='sudo shutdown -h +180'
alias sh4='sudo shutdown -h +240'



alias s0="sudo shutdown -h +9000000;echo''; echo $'Redémarrage annulé';echo''"


alias note="gedit ~/notes/notes.txt"

# VPN CINESITE



#alias cs1="/mnt/c/'Program Files'/Fortinet/FortiClient/'FortiClient VPN'/FortiClient.exe &"
#alias cs2="/mnt/c/'Program Files'/HP/'Remote Graphics Receiver'/rgreceiver.exe &"

# SSH

alias ser="sudo ssh fabrice@192.168.0.180"
alias ttttt="sudo ssh fabrice@192.168.0.180 sudo su -S"

# 




# GIT

alias gitp="git push -u origin master"






alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias ......="cd ../../../../.."
alias .......="cd ../../../../../.."
alias ........="cd ../../../../../../.."
alias .........="cd ../../../../../../../.."
alias ..........="cd ../../../../../../../../.."
alias ...........="cd ../../../../../../../../../.."



# ----------------------------------------------------------------------------------------------------------------------
# PIPELINE
# ----------------------------------------------------------------------------------------------------------------------






#alias mnt="sudo mount -t drvfs //SERVER/PIPELINE /mnt/PIPELINE;
#           sudo mount -t drvfs //SERVER/TEMP /mnt/TEMP"

# NAVIGATION :

alias gosoft="cd $ROOT_DISC; tre 1"
alias godisc="godiscipline; tre 1"
#alias goname="cd $ROOT_TYPE; tre 1"
#alias gotype="cd $ROOT_PROJ; tre 1"
alias goproj="cd $ROOT_PROJ; tre 1"

ref ()
{
    path="$ROOT_PIPE/projs/$TYPE/$NAME/01_ref"
    cd $path
    cd -; cl
}


alias ci1="cd /media/partage/CINEMA_01"
alias ci2="cd /media/partage/CINEMA_02"
alias tmp="cd /media/partage/TEMP"
alias dow="cd /media/partage/DOWNLOADS"
alias pipe="cd /media/partage/PIPELINE"
alias med="cd /media/partage/MEDIA"
alias sto="cd /media/partage/STORAGE"
alias tut="cd /media/partage/PIPELINE/ref/_TUTOS"





# ----------------------------------------------------------------------------------------------------------------------
# A TESTER
# ----------------------------------------------------------------------------------------------------------------------

alias shut="sudo shutdown -h now"








## BIN :
#alias tr='source $BIN/prog/pipe-ui/data/transfert.sh'
#
#alias p3="python3.6"
#alias ptest='cd ~/bin/prog/_training/Test/test_ui/; p3 executer.py &'
#alias sa='cd ~/bin/prog/pipe-ui/; p3 exec.py; cd - &'
#alias sat='cd ~/bin/prog/pipe-ui/; p3 load_form_ui.py; cd - &'
#
#alias un='fmbrc'
#
#alias deux='fmrc'
#

#
#
#
## MAIN :
#
#alias j='job'
#
#
#

#
#alias rmm='rm -Rf'
#alias ddu="du -h -d 1"
#
#alias nau="nn"
#alias py="python"
#

#
#
#
#
#
#
#
## PIPE
#
##alias run='job'
#alias jh='job -h'
#alias jha='job -ha' ###### ??
#alias kp="killpipe"
#alias jl="jll"
#
#alias s="setproj"
#alias sp="setproj"
#alias s1="setproj"
#
#alias jj="setshot"
#alias ss="setshot"
#alias s2="setshot"
#
#alias jjj="setdiscipline"
#alias sss="setdiscipline"
#alias sd="setdiscipline"
#alias s3="setdiscipline"
#
#
#
## SOFTS :
#

#alias ge='gedit'
#alias gd='gedit'
#
#
### SE DEPLACER :
#
#alias tyty="cd $BIN/prog/_training/Test/"
#
#
##alias gocache="cd $CACHE"
##alias gorender="cd $RENDER"
#
#alias goc='gocache'
#alias gor='gorender'
#alias goz='gozbrush'
#
#alias hip="gohip"
#
#alias cin="clear; cd /cygdrive/k; cll"
#alias pipe="cd $PIPE_ROOT"
#
#
#
## PRATIQUE :
#
#alias shtd="$ROOTC/WINDOWS/system32/shutdown.exe -s"
#
#alias brc="$EDITOR /home/$USER/.bashrc"
#alias brcs="source /home/$USER/.bashrc"
#alias sv="$EDITOR '$BIN/backup/savedFiles.txt'"
#
#
#alias d1='du --max-depth=1 -h'
#alias d2='du --max-depth=2 -h'
#
#
## PROG
#
alias pycin="python $BIN/../prog/cineteque/main2.py"
#
#
#
## NON TRIE
#
#alias bin="cd $BIN; clear; echo 'BIN :';echo '====='; ls -lah"
#alias binl="cd /home/$USER/bin; echo 'BIN LOCAL:';echo '==========='; ls -lah"
#
#alias rf="cd $SHOT_PATH/divers/ref; nn"
