#!/usr/bin/env bash
#!/bin/bash



# NAVIGATION
# =========================================================

alias tuto="clear; cd /Volumes/Pipeline/ref/_TUTOS/HOUDINI/; ls -la"



# SYSTEM
# =========================================================

alias nn="open ."



# PIPE
# =========================================================

alias t="run type"
alias p="run proj"
alias f="run fold"
alias s="run soft"

alias r="run"

alias kp="killpipe"




































# system=$OSTYPE

#if [[ $system == "linux-gnu" ]];then
#    system="linux"
#elif [[ $system == "darwin21" ]];then
#    system="mac"
#fi

#export SYSTEM=$system




alias test="python $BIN/gui/main.py"
alias interface="python $BIN/gui/main.py"


# ======================================================================================================================
# ======================================================================================================================
# ======================================================================================================================
#      COMMUN
# ======================================================================================================================
# ======================================================================================================================
# ======================================================================================================================
# ======================================================================================================================
# ======================================================================================================================
# ======================================================================================================================

export EDITOR='gedit'

alias i="init"
alias i0="init 0"
alias i1="init 1"
alias i2="init 2"
alias i3="init 3"

alias ~='cd ~'



# SCRIPTS

# alias python="python3"
alias py='python'

alias tst="python $BIN/python_tools/presse_papier.py"
alias msc="python3 /home/fabrice/bin/music/test2.py"

alias pycin="python $BIN/../prog/cineteque/main2.py"


# SYSTEME

alias ls="ls --color=auto"
alias l="ls -lAvh"
alias cl="clear"
alias cll="clear; l"
alias bin="cd $BIN; clear; echo 'BIN :';echo '====='; ls -lah"
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias ......="cd ../../../../.."
alias .......="cd ../../../../../.."
alias ........="cd ../../../../../../.."
alias .........="cd ../../../../../../../.."
alias ..........="cd ../../../../../../../../.."
alias ...........="cd ../../../../../../../../../.."

export SERVER="192.168.0.180"


# SSH

alias ser="sudo ssh fabrice@192.168.0.180"
alias ttttt="sudo ssh fabrice@192.168.0.180 sudo su -S"



# GIT

alias gitp="git push -u origin master"



# PIPELINE

# alias jh="job -h"
# alias jhh="job -ha"
alias s="setproj"
alias ss="settype"
alias sss="setname"
alias ssss="setdiscipline"



# ======================================================================================================================
# ======================================================================================================================
# ======================================================================================================================
#      MAC
# ======================================================================================================================
# ======================================================================================================================
# ======================================================================================================================
# ======================================================================================================================
# ======================================================================================================================
# ======================================================================================================================

alias gedit="/Applications/Sublime\ Text.app/Contents/MacOS/sublime_text"



# SYSTEME

alias ed="$EDITOR '$BIN/ed/mac/aliases_mac'"
alias ed2="$EDITOR '$BIN/ed/mac/softs_mac'"
alias eds="source $BIN/ed/mac/aliases_mac;source $BIN/ed/mac/softs_mac"




alias brc="$EDITOR '/users/fabrice/.bash_profile'"



# LINUX A GARDER

# alias @='cd $ROOT_C/Users/fabrice'
# alias @@='cd $ROOT_C/Users/fabrice/fabrice'
# LS_COLORS="di=34;1"     # :ln=36;1:ex=31;1:*~=31;1:*.html=31;1:*.shtml=37;1"
# export LS_COLORS        # Couleur de fichiers dossiers dans le terminal
# alias smb="$EDITOR /etc/samba/smb.conf"
# alias fst="$EDITOR /etc/fstab"
# alias ram="free -h && sysctl vm.drop_caches=3 && free -h"



# A TESTER
alias s0="sudo shutdown -h +9000000;echo''; echo $'Redémarrage annulé';echo''"
alias s1='sudo shutdown -h +60'
alias s2='sudo shutdown -h +120'
alias s3='sudo shutdown -h +180'
alias s4='sudo shutdown -h +240'
alias shut="sudo shutdown -h now"









#"C:\Program Files\DJV2\bin\djv.exe"






# 
















# ----------------------------------------------------------------------------------------------------------------------
# PIPELINE
# ----------------------------------------------------------------------------------------------------------------------





#alias mnt="sudo mount -t drvfs //SERVER/PIPELINE /mnt/PIPELINE;
#           sudo mount -t drvfs //SERVER/TEMP /mnt/TEMP"

# NAVIGATION :

alias gosoft="cd $ROOT_DISC; tre 1"
alias godisc="godiscipline; tre 1"
#alias goname="cd $ROOT_TYPE; tre 1"
#alias gotype="cd $ROOT_PROJ; tre 1"
alias goproj="cd $ROOT_PROJ; tre 1"
# ----------------------------------------------------------------------------------------------------------------------
# A TESTER
# ----------------------------------------------------------------------------------------------------------------------










## BIN :
#alias tr='source $BIN/prog/pipe-ui/data/transfert.sh'
#
#alias p3="python3.6"
#alias ptest='cd ~/bin/prog/_training/Test/test_ui/; p3 executer.py &'
#alias sa='cd ~/bin/prog/pipe-ui/; p3 exec.py; cd - &'
#alias sat='cd ~/bin/prog/pipe-ui/; p3 load_form_ui.py; cd - &'
#
#alias un='fmbrc'
#
#alias deux='fmrc'
#

#
#
#
## MAIN :
#
#alias j='job'
#
#
#

#
#alias rmm='rm -Rf'
#alias ddu="du -h -d 1"
#
#alias nau="nn"
#alias py="python"
#

#
#
#
#
#
#
#
## PIPE
#
##alias run='job'
#alias jh='job -h'
#alias jha='job -ha' ###### ??
#alias kp="killpipe"
#alias jl="jll"
#
#alias s="setproj"
#alias sp="setproj"
#alias s1="setproj"
#
#alias jj="setshot"
#alias ss="setshot"
#alias s2="setshot"
#
#alias jjj="setdiscipline"
#alias sss="setdiscipline"
#alias sd="setdiscipline"
#alias s3="setdiscipline"
#
#
#
## SOFTS :
#

#alias ge='gedit'
#alias gd='gedit'
#
#
### SE DEPLACER :
#
#alias tyty="cd $BIN/prog/_training/Test/"
#
#
##alias gocache="cd $CACHE"
##alias gorender="cd $RENDER"
#
#alias goc='gocache'
#alias gor='gorender'
#alias goz='gozbrush'
#
#alias hip="gohip"
#
#alias cin="clear; cd /cygdrive/k; cll"
#alias pipe="cd $PIPE_ROOT"
#
#
#
## PRATIQUE :
#
#alias shtd="$ROOTC/WINDOWS/system32/shutdown.exe -s"
#
#alias brc="$EDITOR /home/$USER/.bashrc"
#alias brcs="source /home/$USER/.bashrc"
#alias sv="$EDITOR '$BIN/backup/savedFiles.txt'"
#
#
#alias d1='du --max-depth=1 -h'
#alias d2='du --max-depth=2 -h'
#
#

#
#
#
## NON TRIE
#
#alias bin="cd $BIN; clear; echo 'BIN :';echo '====='; ls -lah"
#alias binl="cd /home/$USER/bin; echo 'BIN LOCAL:';echo '==========='; ls -lah"
#
#alias rf="cd $SHOT_PATH/divers/ref; nn"
